### ISSUE TITLE
uninitialized constant EtsyAccount

### ISSUE THREAD

**Issue by ruehsn** [JaceBayless/betsy#3]
```
/usr/share/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.7/lib/active_support/inflector/methods.rb:278:in `constantize': uninitialized constant EtsyAccount (NameError)

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
        from /usr/share/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.7/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/betsy-0.2.1/lib/betsy.rb:110:in `account_class'
        from (erb):3:in `migration_template'
        from /usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/erb.rb:429:in `eval'
        from /usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/erb.rb:429:in `result'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/generators/migration.rb:66:in `block in migration_template'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions/create_file.rb:53:in `render'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions/create_file.rb:63:in `open'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions/create_file.rb:63:in `block in invoke!'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions/create_file.rb:60:in `invoke!'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/generators/actions/create_migration.rb:25:in `invoke!'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/actions.rb:93:in `action'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/generators/migration.rb:36:in `create_migration'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/generators/migration.rb:65:in `migration_template'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/betsy-0.2.1/lib/generators/betsy/install_generator.rb:19:in `copy_betsy_migration'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `block in invoke_all'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `each'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `map'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `invoke_all'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/group.rb:232:in `dispatch'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/generators.rb:263:in `invoke'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/command/base.rb:87:in `perform'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/command.rb:48:in `invoke'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/railties-7.0.7/lib/rails/commands.rb:18:in `<main>'
        from <internal:/usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/share/rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/share/rvm/gems/ruby-3.2.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

This is on a fresh Rails 7 app when trying to run:
`rails generate betsy:install`

Thanks for making gem that is compatiable with Etsy v3 API!

**Comment by ruehsn** [comment]
Same issue on Rails 6 fresh app both using Ruby 3.2... trying to recreate Rails 6 with Ruby 3.0 on Ubuntu.  Can you confirm the version of Ruby/Rails that this gem worked under?

As a work around, could you provide high level overview of what the generate does?  Perhaps I could do that work manually.
